short Atari2Unicode[] = {
	/* ISO/IEC 10646-1:2000 (UNICODE) Character Name */
0,	/* (Nothing) */
8679,	/* UPWARDS WHITE ARROW */
8681,	/* DOWNWARDS WHITE ARROW */
8680,	/* RIGHTWARDS WHITE ARROW */
8678,	/* LEFTWARDS WHITE ARROW */
0,
0,
0,
10003,	/* CHECK MARK */
9719,	/* WHITE CIRCLE WITH UPPER RIGHT QUADRANT */
9086,	/* BELL SYMBOL */
9834,	/* EIGHTH NOTE */
9228,	/* SYMBOL FOR FORM FEED */
9229,	/* SYMBOL FOR CARRIAGE RETURN */
9565,	/* BOX DRAWINGS DOUBLE UP AND LEFT (Fuji left) */
9562,	/* BOX DRAWINGS DOUBLE UP AND RIGHT (Fuji right) */
9450,	/* CIRCLED DIGIT ZERO */
9312,	/* CIRCLED DIGIT ONE */
9313,	/* CIRCLED DIGIT TWO */
9314,	/* CIRCLED DIGIT THREE */
9315,	/* CIRCLED DIGIT FOUR */
9316,	/* CIRCLED DIGIT FIVE */
9317,	/* CIRCLED DIGIT SIX */
9318,	/* CIRCLED DIGIT SEVEN */
9319,	/* CIRCLED DIGIT EIGHT */
9320,	/* CIRCLED DIGIT NINE */
8364,	/* EURO SIGN (Upside down small E) */
9243,	/* SYMBOL FOR ESCAPE */
9581,	/* BOX DRAWINGS LIGHT ARC DOWN AND RIGHT (Face upper left) */
9582,	/* BOX DRAWINGS LIGHT ARC DOWN AND LEFT (Face upper right) */
9583,	/* BOX DRAWINGS LIGHT ARC UP AND LEFT (Face lower left) */
9584,	/* BOX DRAWINGS LIGHT ARC UP AND RIGHT (Face lower right) */
32,	/* SPACE */
33,	/* EXCLAMATION MARK */
34,	/* QUOTATION MARK */
35,	/* NUMBER SIGN */
36,	/* DOLLAR SIGN */
37,	/* PERCENT SIGN */
38,	/* AMPERSAND */
39,	/* APOSTROPHE */
40,	/* LEFT PARENTHESIS */
41,	/* RIGHT PARENTHESIS */
42,	/* ASTERISK */
43,	/* PLUS SIGN */
44,	/* COMMA */
45,	/* HYPHEN-MINUS */
46,	/* FULL STOP */
47,	/* SOLIDUS */
48,	/* DIGIT ZERO */
49,	/* DIGIT ONE */
50,	/* DIGIT TWO */
51,	/* DIGIT THREE */
52,	/* DIGIT FOUR */
53,	/* DIGIT FIVE */
54,	/* DIGIT SIX */
55,	/* DIGIT SEVEN */
56,	/* DIGIT EIGHT */
57,	/* DIGIT NINE */
58,	/* COLON */
59,	/* SEMICOLON */
60,	/* LESS-THAN SIGN */
61,	/* EQUALS SIGN */
62,	/* GREATER-THAN SIGN */
63,	/* QUESTION MARK */
64,	/* COMMERCIAL AT */
65,	/* LATIN CAPITAL LETTER A */
66,	/* LATIN CAPITAL LETTER B */
67,	/* LATIN CAPITAL LETTER C */
68,	/* LATIN CAPITAL LETTER D */
69,	/* LATIN CAPITAL LETTER E */
70,	/* LATIN CAPITAL LETTER F */
71,	/* LATIN CAPITAL LETTER G */
72,	/* LATIN CAPITAL LETTER H */
73,	/* LATIN CAPITAL LETTER I */
74,	/* LATIN CAPITAL LETTER J */
75,	/* LATIN CAPITAL LETTER K */
76,	/* LATIN CAPITAL LETTER L */
77,	/* LATIN CAPITAL LETTER M */
78,	/* LATIN CAPITAL LETTER N */
79,	/* LATIN CAPITAL LETTER O */
80,	/* LATIN CAPITAL LETTER P */
81,	/* LATIN CAPITAL LETTER Q */
82,	/* LATIN CAPITAL LETTER R */
83,	/* LATIN CAPITAL LETTER S */
84,	/* LATIN CAPITAL LETTER T */
85,	/* LATIN CAPITAL LETTER U */
86,	/* LATIN CAPITAL LETTER V */
87,	/* LATIN CAPITAL LETTER W */
88,	/* LATIN CAPITAL LETTER X */
89,	/* LATIN CAPITAL LETTER Y */
90,	/* LATIN CAPITAL LETTER Z */
91,	/* LEFT SQUARE BRACKET */
92,	/* REVERSE SOLIDUS */
93,	/* RIGHT SQUARE BRACKET */
94,	/* CIRCUMFLEX ACCENT */
95,	/* LOW LINE */
96,	/* GRAVE ACCENT */
97,	/* LATIN SMALL LETTER A */
98,	/* LATIN SMALL LETTER B */
99,	/* LATIN SMALL LETTER C */
100,	/* LATIN SMALL LETTER D */
101,	/* LATIN SMALL LETTER E */
102,	/* LATIN SMALL LETTER F */
103,	/* LATIN SMALL LETTER G */
104,	/* LATIN SMALL LETTER H */
105,	/* LATIN SMALL LETTER I */
106,	/* LATIN SMALL LETTER J */
107,	/* LATIN SMALL LETTER K */
108,	/* LATIN SMALL LETTER L */
109,	/* LATIN SMALL LETTER M */
110,	/* LATIN SMALL LETTER N */
111,	/* LATIN SMALL LETTER O */
112,	/* LATIN SMALL LETTER P */
113,	/* LATIN SMALL LETTER Q */
114,	/* LATIN SMALL LETTER R */
115,	/* LATIN SMALL LETTER S */
116,	/* LATIN SMALL LETTER T */
117,	/* LATIN SMALL LETTER U */
118,	/* LATIN SMALL LETTER V */
119,	/* LATIN SMALL LETTER W */
120,	/* LATIN SMALL LETTER X */
121,	/* LATIN SMALL LETTER Y */
122,	/* LATIN SMALL LETTER Z */
123,	/* LEFT CURLY BRACKET */
124,	/* VERTICAL LINE */
125,	/* RIGHT CURLY BRACKET */
126,	/* TILDE */
916,	/* GREEK CAPITAL LETTER DELTA */
/* 9651,	WHITE UP-POINTING TRIANGLE */
199,	/* LATIN CAPITAL LETTER C WITH CEDILLA */
252,	/* LATIN SMALL LETTER U WITH DIAERESIS */
233,	/* LATIN SMALL LETTER E WITH ACUTE */
226,	/* LATIN SMALL LETTER A WITH CIRCUMFLEX */
228,	/* LATIN SMALL LETTER A WITH DIAERESIS */
224,	/* LATIN SMALL LETTER A WITH GRAVE */
229,	/* LATIN SMALL LETTER A WITH RING ABOVE */
231,	/* LATIN SMALL LETTER C WITH CEDILLA */
234,	/* LATIN SMALL LETTER E WITH CIRCUMFLEX */
235,	/* LATIN SMALL LETTER E WITH DIAERESIS */
232,	/* LATIN SMALL LETTER E WITH GRAVE */
239,	/* LATIN SMALL LETTER I WITH DIAERESIS */
238,	/* LATIN SMALL LETTER I WITH CIRCUMFLEX */
236,	/* LATIN SMALL LETTER I WITH GRAVE */
196,	/* LATIN CAPITAL LETTER A WITH DIAERESIS */
197,	/* LATIN CAPITAL LETTER A WITH RING ABOVE */
201,	/* LATIN CAPITAL LETTER E WITH ACUTE */
230,	/* LATIN SMALL LETTER AE */
198,	/* LATIN CAPITAL LETTER AE */
244,	/* LATIN SMALL LETTER O WITH CIRCUMFLEX */
246,	/* LATIN SMALL LETTER O WITH DIAERESIS */
242,	/* LATIN SMALL LETTER O WITH GRAVE */
251,	/* LATIN SMALL LETTER U WITH CIRCUMFLEX */
249,	/* LATIN SMALL LETTER U WITH GRAVE */
255,	/* LATIN SMALL LETTER Y WITH DIAERESIS */
214,	/* LATIN CAPITAL LETTER O WITH DIAERESIS */
220,	/* LATIN CAPITAL LETTER U WITH DIAERESIS */
162,	/* CENT SIGN */
163,	/* POUND SIGN */
165,	/* YEN SIGN */
223,	/* LATIN SMALL LETTER SHARP S */
402,	/* LATIN SMALL LETTER F WITH HOOK */
225,	/* LATIN SMALL LETTER A WITH ACUTE */
237,	/* LATIN SMALL LETTER I WITH ACUTE */
243,	/* LATIN SMALL LETTER O WITH ACUTE */
250,	/* LATIN SMALL LETTER U WITH ACUTE */
241,	/* LATIN SMALL LETTER N WITH TILDE */
209,	/* LATIN CAPITAL LETTER N WITH TILDE */
170,	/* FEMININE ORDINAL INDICATOR */
186,	/* MASCULINE ORDINAL INDICATOR */
191,	/* INVERTED QUESTION MARK */
8976,	/* REVERSED NOT SIGN */
172,	/* NOT SIGN */
189,	/* VULGAR FRACTION ONE HALF */
188,	/* VULGAR FRACTION ONE QUARTER */
161,	/* INVERTED EXCLAMATION MARK */
171,	/* LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
187,	/* RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
227,	/* LATIN SMALL LETTER A WITH TILDE */
245,	/* LATIN SMALL LETTER O WITH TILDE */
216,	/* LATIN CAPITAL LETTER O WITH STROKE */
248,	/* LATIN SMALL LETTER O WITH STROKE */
339,	/* LATIN SMALL LIGATURE OE */
338,	/* LATIN CAPITAL LIGATURE OE */
192,	/* LATIN CAPITAL LETTER A WITH GRAVE */
195,	/* LATIN CAPITAL LETTER A WITH TILDE */
213,	/* LATIN CAPITAL LETTER O WITH TILDE */
168,	/* DIAERESIS */
180,	/* ACUTE ACCENT */
8224,	/* DAGGER */
182,	/* PILCROW SIGN */
169,	/* COPYRIGHT SIGN */
174,	/* REGISTERED SIGN */
8482,	/* TRADE MARK SIGN */
307,	/* LATIN SMALL LIGATURE IJ */
306,	/* LATIN CAPITAL LIGATURE IJ */
1488,	/* HEBREW LETTER ALEF */
1489,	/* HEBREW LETTER BET */
1490,	/* HEBREW LETTER GIMEL */
1491,	/* HEBREW LETTER DALET */
1492,	/* HEBREW LETTER HE */
1493,	/* HEBREW LETTER VAV */
1494,	/* HEBREW LETTER ZAYIN */
1495,	/* HEBREW LETTER HET */
1496,	/* HEBREW LETTER TET */
1497,	/* HEBREW LETTER YOD */
1499,	/* HEBREW LETTER KAF */
1500,	/* HEBREW LETTER LAMED */
1502,	/* HEBREW LETTER MEM */
1504,	/* HEBREW LETTER NUN */
1505,	/* HEBREW LETTER SAMEKH */
1506,	/* HEBREW LETTER AYIN */
1508,	/* HEBREW LETTER PE */
1510,	/* HEBREW LETTER TSADI */
1511,	/* HEBREW LETTER QOF */
1512,	/* HEBREW LETTER RESH */
1513,	/* HEBREW LETTER SHIN */
1514,	/* HEBREW LETTER TAV */
1503,	/* HEBREW LETTER FINAL NUN */
1498,	/* HEBREW LETTER FINAL KAF */
1501,	/* HEBREW LETTER FINAL MEM */
1507,	/* HEBREW LETTER FINAL PE */
1509,	/* HEBREW LETTER FINAL TSADI */
167,	/* SECTION SIGN */
8743,	/* LOGICAL AND */
8734,	/* INFINITY */
945,	/* GREEK SMALL LETTER ALPHA */
946,	/* GREEK SMALL LETTER BETA */
915,	/* GREEK CAPITAL LETTER GAMMA */
960,	/* GREEK SMALL LETTER PI */
931,	/* GREEK CAPITAL LETTER SIGMA */
963,	/* GREEK SMALL LETTER SIGMA */
181,	/* MICRO SIGN */
964,	/* GREEK SMALL LETTER TAU */
934,	/* GREEK CAPITAL LETTER PHI */
920,	/* GREEK CAPITAL LETTER THETA */
937,	/* GREEK CAPITAL LETTER OMEGA */
948,	/* GREEK SMALL LETTER DELTA */
8750,	/* CONTOUR INTEGRAL */
966,	/* GREEK SMALL LETTER PHI */
949,	/* GREEK SMALL LETTER EPSILON */
8745,	/* INTERSECTION */
8801,	/* IDENTICAL TO */
177,	/* PLUS-MINUS SIGN */
8805,	/* GREATER-THAN OR EQUAL TO */
8804,	/* LESS-THAN OR EQUAL TO */
8992,	/* TOP HALF INTEGRAL */
8993,	/* BOTTOM HALF INTEGRAL */
247,	/* DIVISION SIGN */
8776,	/* ALMOST EQUAL TO */
176,	/* DEGREE SIGN */
8729,	/* BULLET OPERATOR */
183,	/* MIDDLE DOT */
8730,	/* SQUARE ROOT */
8319,	/* SUPERSCRIPT LATIN SMALL LETTER N */
178,	/* SUPERSCRIPT TWO */
179,	/* SUPERSCRIPT THREE */
175	/* MACRON */
};
